# Generated by Django 5.1.1 on 2024-10-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts_of_nature', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP-адрес')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts_of_nature.publication', verbose_name='Публикация')),
            ],
        ),
    ]
