# Generated by Django 5.1.1 on 2024-10-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts_of_nature', '0004_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Дизлайк'},
        ),
        migrations.AlterField(
            model_name='likes',
            name='ip',
            field=models.CharField(max_length=50, verbose_name='IP-адрес'),
        ),
    ]
