# Generated by Django 5.1.1 on 2024-10-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts_of_nature', '0005_alter_likes_options_alter_likes_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('ip', 'posts')},
        ),
    ]
